# Made by BGHDDevelopment
#=======================================================
#Plugin Page: https://www.spigotmc.org/resources/46678
#=======================================================

Messages:
  Message1: '&e&lKABOOM!'
#Message sent to all players when /kaboom is used
#Set to '' to disable
#=======================================================
#Plugin Commands:
# /kaboom - kaboom.use
# /kaboom reload - kaboom.reload
#Permission:
# kaboom.bypass - Bypass /kaboom