name: Kaboom
version: ${project.version}
main: me.noodles.boom.Kaboom
authors: [BGHDDevelopment]
website: https://bghddevelopment.com/
commands:
  kaboom:
    description: Fling players
    usage: /<command> <reload>